name: bi-weekly-cron
on:
  schedule:
    - cron: "00 8 * * 1,4,7"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the function
        run: |
          curl --request GET \
          --url 'https://send-quotes.vercel.app/api/quote' \
